#speech commands dataset, represented by python lists
IncreaseVolume = ["increase the volume","turn up the volume","increase volume","increase sound","i need more sound"]
VolumeMute = ["mute the volume","mute","mute volume","mute sound","no sound"]
VolumeUnMute = ["unmute the volume","unmute","unmute volume","full volume","set volume to full","set volume to maximum"]
DecreaseVolume = ["decrease the volume","turn down the volume","decrease volume","decrease sound"]
IncreaseBrightness = ["increase the brightness","turn up the brightness","increase brightness"]
DecreaseBrightness = ["decrease the brightness","turn down the brightness","decrease brightness","low brightness"]
FullBrightness = ["set the maximum brightness","turn up the brightness to maximum","maximum brightness","full brightness"]
FullLowBrightness = ["set the minimum brightness","turn down the brightness to minimum","minimum brightness","full low brightness"]
HalfVolume = ["half the volume","set volume to half","half volume","set half volume"]
BrightnessHalf = ["half the brightness","set brightness to half","half brightness","set half brightness"]
Stop = ["stop","top","close the service","end the service"]
start = ["start","start services"]
stopCode = ["exit code","stop the program","exit","exit program"]
Yes = ["yes","yes stop the service","yes end the service","yes stop the program","yeah i want","yeah"]
No = ["no","i said by mistake","no i dont want","no i said by mistake","no i said by mistake sorry","nope"]